apiVersion: v1
kind: Secret
metadata:
  name: auth-ui-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KEYCLOAK_BASE: {{ .Values.keycloak.base | quote }}
  CLIENT_ID: {{ .Values.keycloak.clientId | quote }}
  CLIENT_SECRET: {{ .Values.keycloak.clientSecret | quote }}
  REDIRECT_URI: {{ .Values.redirectUri | quote }}
  HERMES_HOME: {{ .Values.hermesHome | quote }}
  GITEA_URL: {{ .Values.giteaUrl | quote }}
  SLACK_URL: {{ .Values.slackUrl | quote }}
