apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceentry.yaml
  - destinationrule.yaml
  - httproute-atlassian.yaml
  - mcpsr-atlassian.yaml
  - authpolicy-atlassian.yaml
  - atlassian-token-refresher.yaml
