apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: sdxl
  namespace: {{ .Release.Namespace }}
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: SDXL Runtime
    opendatahub.io/template-name: sdxl
    openshift.io/display-name: SDXL Runtime
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  multiModel: false
  supportedModelFormats:
    - name: sdxl
      autoSelect: true
  containers:
    - name: kserve-container
      image: quay.io/rh-aiservices-bu/sdxl-serving-runtime:0.1.10
      ports:
        - name: http1
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
