{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mem0.postgres.fullname" . }}-pvc
  labels:
    {{- include "mem0.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: {{ .Values.postgres.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
{{- end }}
