{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mem0.postgres.fullname" . }}
  labels:
    {{- include "mem0.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "mem0.postgres.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
