---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.agent.name }}-data
  namespace: {{ .Values.agent.namespace }}
  labels:
    app: {{ .Values.agent.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
